
services:
  seed-node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kodechain-seed-node
    ports:
      - "${SEED_PORT:-3000}:3000"
    environment:
      - PORT=${SEED_PORT:-3000}
      - DATA_DIR=/data
      - DB_PATH=/data/nodes.db
      - CONFIG_PATH=/data/seed_config.json
      - CHECK_INTERVAL=${CHECK_INTERVAL:-30s}
      - PRUNE_INTERVAL=${PRUNE_INTERVAL:-2h}
      - PRUNE_AGE=${PRUNE_AGE:-4h}
      - MAX_NODES=${MAX_NODES:-100}
    volumes:
      - seed_data:/data
    command: >
      ./main 
      -port=3000
      -datadir=/data
      -check=${CHECK_INTERVAL:-30s}
      -prune=${PRUNE_INTERVAL:-2h}
      -pruneage=${PRUNE_AGE:-4h}
    networks:
      - kodechain-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  seed_data:
    driver: local

networks:
  kodechain-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16